services:
  app:
    container_name: pfm-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      UVICORN_HOST: ${UVICORN_HOST}
      UVICORN_PORT: ${UVICORN_PORT}
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    command:
      sh -c "
      alembic upgrade head &&
      uvicorn src.run:create_app --host ${UVICORN_HOST} --port ${UVICORN_PORT} --loop uvloop
      "

  postgres:
    image: postgres:17-alpine
    container_name: pfm-postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pg_data:
    driver: local
